### ISSUE TITLE
Expired SSL Certificate

### ISSUE THREAD

**Issue by DefinetlyNotAI** [FlipperMaker/flippermaker.github.io#28]
Error while downloading:-
```http
Your connection is not private
Attackers might be trying to steal your information from dev.flpr.app (for example, passwords, messages, or credit cards).

NET::ERR_CERT_COMMON_NAME_INVALID
```

I have the cert with me, changed to txt for uploading, change it back to crt later,
[alcs-t.maxserv.dev.txt](https://github.com/user-attachments/files/16533687/alcs-t.maxserv.dev.txt)

I have tried incognito, erasing my cookies and cache, reloading etc

This occured while downloading subghz with button 0 and code brute, web works perfect, download web fails

IK this is old (2 yrs ago)

**Comment by corbanmailloux** [comment]
@DefinetlyNotAI I see you closed this. Did you find other information or a workaround? 

I'm sad to see FlipperMaker die with how many people link to it in the Flipper Discord servers.

**Comment by DefinetlyNotAI** [comment]
I know - but sadly i used the wayback machine as workaround

But as you can tell DDoS attacks on the website wayback machine is down
